# Generated by Django 3.0.7 on 2020-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcos_medication', models.CharField(max_length=1000)),
                ('other_medication', models.CharField(max_length=1000)),
                ('allergies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Menstrual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_period_age', models.IntegerField()),
                ('last_period_date', models.DateField()),
                ('cycle_length', models.IntegerField()),
                ('period_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menstrual_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_first_period', models.IntegerField()),
                ('date_last_period', models.DateField()),
                ('cycle_len', models.IntegerField()),
                ('period_len', models.IntegerField()),
                ('flow_amount', models.CharField(default='Medium', max_length=100)),
                ('pain_scale', models.CharField(default='Medium', max_length=100)),
                ('bleeding', models.CharField(default='no', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pcos_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcos_diagnosed_age', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose_of_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('add_reason', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_age', models.IntegerField()),
            ],
        ),
    ]
