# Generated by Django 3.0.7 on 2020-06-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menstrual_hist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menstrual',
        ),
        migrations.DeleteModel(
            name='Menstrual_Hist',
        ),
        migrations.DeleteModel(
            name='Menstrual_History',
        ),
    ]
