# Generated by Django 3.0.7 on 2020-06-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mensis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensis',
            name='m_bleeding',
        ),
    ]
