# Generated by Django 3.0.7 on 2020-06-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mensis_m_bleed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensis',
            name='m_bleed',
        ),
    ]
