# Generated by Django 3.0.7 on 2020-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_mensis_m_bleed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcos_history',
            name='pcos_diagnosed_age',
            field=models.CharField(default='less than 20', max_length=128),
        ),
    ]
