# Generated by Django 3.0.7 on 2020-06-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200622_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcos_history',
            name='test',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
