# Generated by Django 3.0.7 on 2020-06-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pcos_history_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcos_history',
            old_name='test',
            new_name='q1_check1',
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='q1_check2',
            field=models.CharField(default='def', max_length=100),
        ),
    ]
