# Generated by Django 3.0.7 on 2020-06-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200622_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcos_history',
            name='diff_conceiving',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='hair_loss',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='irr_period',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='none',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='other',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='poly_cystic_ovaries',
        ),
        migrations.RemoveField(
            model_name='pcos_history',
            name='weight_gain',
        ),
    ]
