# Generated by Django 3.0.7 on 2020-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200622_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcos_history',
            name='acne',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='pcos_history',
            name='excess_hair_growth',
            field=models.CharField(default='def', max_length=100),
        ),
    ]
