# Generated by Django 3.0.7 on 2020-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200622_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcos_history',
            name='acne',
            field=models.CharField(blank=True, default='abc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcos_history',
            name='excess_hair_growth',
            field=models.CharField(blank=True, default='def', max_length=100, null=True),
        ),
    ]
