# Generated by Django 3.0.7 on 2020-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200622_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcos_history',
            name='diff_conceiving',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='hair_loss',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='irr_period',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='none',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='other',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='poly_cystic_ovaries',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='weight_gain',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcos_history',
            name='acne',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcos_history',
            name='excess_hair_growth',
            field=models.CharField(blank=True, default='not_correct', max_length=100, null=True),
        ),
    ]
