# Generated by Django 3.0.7 on 2020-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200622_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcos_history',
            name='feel_of_guilt',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='headaches',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='hypothyroidism',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='lactation',
            field=models.CharField(blank=True, default='appropriate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='sex_drive',
            field=models.CharField(blank=True, default='normal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='skin_tag_armpit',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='sleeping_disorder',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcos_history',
            name='sudden_hunger',
            field=models.CharField(blank=True, default='not_there', max_length=100, null=True),
        ),
    ]
