# Generated by Django 3.0.7 on 2020-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200622_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensis',
            name='m_bleed',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
