# Generated by Django 3.0.7 on 2020-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200622_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose_of_visit',
            name='docfile',
            field=models.FileField(default='none', upload_to='documents/'),
        ),
    ]
